/* src/tool_config.h
 *
 * Per-tool compile-time configuration. Normally generated by install.ps1
 * immediately before each build. The committed version is a DEV STUB
 * containing Claude Code defaults so the source compiles standalone
 * during development.
 */
#ifndef TOOL_CONFIG_H
#define TOOL_CONFIG_H

#define TOOL_EXE_PATH       L"claude.exe"
#define TOOL_PARENT_TITLE   L"Claude Code"
#define TOOL_PARENT_TOOLTIP L"Claude Code options"

static const GUID CLSID_Tool = {
    0xE3C26D71, 0x5A2F, 0x4B89,
    {0x9C, 0x7E, 0xA1, 0xD3, 0xF6, 0xB8, 0x4E, 0x52}
};

typedef struct {
    const wchar_t *title;
    const wchar_t *tooltip;
    const wchar_t *args;  /* NULL = no extra args */
} MenuItemDef;

static const MenuItemDef g_menuItems[] = {
    { L"Open (Default)", L"Launch Claude Code in this folder",                    NULL },
    { L"Open (Auto)",    L"Launch Claude Code with --enable-auto-mode",           L"--enable-auto-mode" },
    { L"Open (YOLO)",    L"Launch Claude Code with --dangerously-skip-permissions", L"--dangerously-skip-permissions" },
};
#define NUM_MENU_ITEMS (sizeof(g_menuItems) / sizeof(g_menuItems[0]))

#endif /* TOOL_CONFIG_H */
